description: >
  Default executor for CircleCI Server Manager jobs

parameters:
  version:
    default: 2023.10.1
    description: The image version to use when executing
    type: string
machine:
  image: ubuntu-2204:<< parameters.version >>
  resource_class: medium
