description: >
  Lorem ipsum dolor sit amet, consectetur adipiscing elit
docker:
  - image: cimg/base:current
parameters:
  tag:
    default: lts
    description: >
      Pick a specific cimg/node image variant:
      https://hub.docker.com/r/cimg/node/tags
    type: string
